---
title: "Francisco Portugal Covid19 EDA"
author: "Jim Porzak"
date: "`r Sys.Date()`"
output: html_notebook
---

### Setup

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, message=FALSE}
library(tidyverse, quietly = TRUE)
library(readr)
library(stringr)
library(lubridate)
library(DBI)
library(dbplyr)
library(RMariaDB)
library(xtable)
library(rvest)
library(xml2)
library(jsonlite)
```

```{r pull}
dgs_cases_url <- "https://services.arcgis.com/CCZiGSEQbAxxFVh3/arcgis/rest/services/COVID19Portugal_view/FeatureServer/0/query?f=json&where=1=1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=datarelatorio asc&resultOffset=0&resultRecordCount=1000"

dgs_geo_url <- "https://services.arcgis.com/CCZiGSEQbAxxFVh3/arcgis/rest/services/COVID19Portugal_view/FeatureServer/1/query?f=json&where=1=1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=dist_casosconf desc&resultOffset=0&resultRecordCount=1000"

dgs_cases <- fromJSON(URLencode(dgs_cases_url))
dgs_geo <- fromJSON(URLencode(dgs_geo_url))

cases_dataset <- dgs_cases[["features"]][["attributes"]]
geo_dataset <- dgs_geo[["features"]][["attributes"]]
```

```{r}
geo_dataset <- dgs_geo[["features"]][["attributes"]] 

geo_colnames <- c("id_objeto", "id_global", "data_relatorio", "distrito", "casos_confirmados", "n_obitos", "recuperados", "id_global_pai", "creation_date", "creator", "edit_date", "editor", "untimo_registo") 

names(geo_dataset) <- geo_colnames 

geo_dataset$data_relatorio <- as.Date(as.POSIXct(geo_dataset$data_relatorio / 1000, origin = "1960-01-01"))

geo_dataset$creation_date <- as.Date(as.POSIXct(geo_dataset$creation_date / 1000, origin = "1960-01-01"))

geo_dataset$edit_date <- as.Date(as.POSIXct(geo_dataset$edit_date / 1000, origin = "1960-01-01")) 

geo_norte <- geo_dataset %>% filter(distrito == "+041.45756_-007.67865") %>% distinct_at(vars(data_relatorio), .keep_all = TRUE) %>% arrange(data_relatorio) %>% mutate(id_objeto = seq(13, n()+13-1)) 

cases_dataset <- dgs_cases[["features"]][["attributes"]]

colnames <- c( "id_objeto", "id_global", "data_relatorio", "casos_confirmados", "n_obitos")
```

