---
title: "Portugal Covid19 EDA"
author: "Jim Porzak"
date: "`r Sys.Date()`"
output: html_notebook
---

### Setup

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, message=FALSE}
library(tidyverse, quietly = TRUE)
library(readr)
library(stringr)
library(lubridate)
library(DBI)
library(dbplyr)
library(RMariaDB)
library(xtable)
library(rvest)
library(xml2)
```

#### Presets
```{r preset}
cv19_pt_pg <- "https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Portugal"
cv19_pt_xpath <- '//*[@id="mw-content-text"]/div/table[4]'
min_cases_to_be_active <- 30

```

## Get Daily Stats Table
Source: `r cv19_pt_pg`
```{r daily}
cv19_pt <- xml2::read_html(cv19_pt_pg)

cv19_pt_tbl0 <- cv19_pt %>% 
  html_nodes(xpath = cv19_pt_xpath) %>% 
  html_table(fill = TRUE)
cv19_pt_tbl0 <- cv19_pt_tbl0[[1]]
cnames0 <- colnames(cv19_pt_tbl0)
cnames <- cnames0
cnames[3] <- "Lisbon_TV"
cnames[10:15] <- c("Confirmed_New", "Confirmed_Tot", 
                   "Deaths_New", "Deaths_Total",
                   "Recoveries_New", "Recoveries_Total")
colnames(cv19_pt_tbl0) <- cnames

## Fix 2020-03-16 Cases
cv19_pt_tbl0[16, 10:12] <- c(86, 331, 1)

cv19_pt_tbl <- cv19_pt_tbl0 %>% 
  select(-Notes) %>% 
  mutate(Date = as_date(Date, format = "%Y-%m-%d", tz = "GMT")) %>% 
  filter(!is.na(Date)) %>% 
  mutate_at(2:14, as.integer) %>% 
  mutate(Confirmed_Pct_Inc = round(100 * Confirmed_New / coalesce(lag(Confirmed_Tot), 0L), 1))
DataAsOf <- max(cv19_pt_tbl$Date)
cv19_pt_tbl
```

## All of Portugal
```{r PctInc}
cv19_pt_tbl %>% 
  filter(is.finite(Confirmed_Pct_Inc)) %>% 
  ggplot(aes(Date, Confirmed_Pct_Inc)) +
    geom_point() +
    geom_smooth() +
    labs(title = "% Change in Confirmed COVID-19 Cases in Portugal",
         subtitle = paste("Source:", cv19_pt_pg),
         y = "% Change",
         caption = paste("As of", DataAsOf))
  

```
## Active Regions
Where these _active_ regions have at least `r min_cases_to_be_active` cases:

```{r subset_regions}
is_active <- function(x) x >= min_cases_to_be_active
cv19_active <- cv19_pt_tbl %>% 
  select(2:9) %>% 
  summarise_all(sum) %>% 
  select_if(is_active) %>% 
  pivot_longer(everything(), names_to = "Region", values_to = "Total_Cases")
cv19_active  
```

